version: "3.8"

volumes:
  mariadb:
    driver: local

services:
  mariadb:
    image: mariadb:10.6
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=snapper
      - MARIADB_USER=snapper
      - MARIADB_PASSWORD=snapper
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    expose:
      - "8080"
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
