version: "3.8"

services:
  mariadb:
    image: mariadb:10.6
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=snapper
      - MARIADB_USER=test
      - MARIADB_PASSWORD=test
    ports:
      - "3307:3307"
