"""add additional clip information

Revision ID: 150d09a2b569
Revises: 2fc4da0ff983
Create Date: 2023-10-22 21:34:43.913091

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "150d09a2b569"
down_revision: Union[str, None] = "2fc4da0ff983"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clip", sa.Column("thumbnail_url", sa.String(length=255), nullable=False)
    )
    op.add_column("clip", sa.Column("title", sa.String(length=512), nullable=False))
    op.add_column("clip", sa.Column("view_count", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("clip", "view_count")
    op.drop_column("clip", "title")
    op.drop_column("clip", "thumbnail_url")
    # ### end Alembic commands ###
