"""Add server defaults

Revision ID: 4af43dcfbc8e
Revises: 4dd8d36159c5
Create Date: 2023-12-21 20:54:53.009277

"""
from typing import Sequence, Union

from sqlalchemy import false, text

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4af43dcfbc8e"
down_revision: Union[str, None] = "4dd8d36159c5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("stream", "is_active", server_default=false())
    op.alter_column("clip", "rating", server_default=text("1.0"))
    op.alter_column("clip", "nr_votes", server_default=text("1"))
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("stream", "is_active", server_default=None)
    op.alter_column("clip", "rating", server_default=None)
    op.alter_column("clip", "nr_votes", server_default=None)
    pass
    # ### end Alembic commands ###
