"""add rating columns to clips

Revision ID: 59a672baca4b
Revises: e7019a700dc5
Create Date: 2023-10-28 17:45:28.019269

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "59a672baca4b"
down_revision: Union[str, None] = "e7019a700dc5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("clip", sa.Column("rating", sa.Float(), nullable=False))
    op.add_column("clip", sa.Column("nr_votes", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("clip", "nr_votes")
    op.drop_column("clip", "rating")
    # ### end Alembic commands ###
