"""add keyword association table

Revision ID: 8cc378d6d76e
Revises: 150d09a2b569
Create Date: 2023-10-24 12:16:08.696679

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8cc378d6d76e"
down_revision: Union[str, None] = "150d09a2b569"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "keyword",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("value", sa.String(length=255), nullable=False),
        sa.Column("image_url", sa.String(length=512), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "stream_keyword_association",
        sa.Column("stream_id", sa.Integer(), nullable=False),
        sa.Column("keyword_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["keyword_id"],
            ["keyword.id"],
        ),
        sa.ForeignKeyConstraint(
            ["stream_id"],
            ["stream.id"],
        ),
        sa.PrimaryKeyConstraint("stream_id", "keyword_id"),
    )
    op.add_column("clip", sa.Column("keyword_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "clip", "keyword", ["keyword_id"], ["id"])
    op.drop_column("clip", "keyword_trigger")
    op.drop_column("stream", "keyword_list")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stream", sa.Column("keyword_list", mysql.VARCHAR(length=1000), nullable=False)
    )
    op.add_column(
        "clip", sa.Column("keyword_trigger", mysql.VARCHAR(length=255), nullable=False)
    )
    op.drop_constraint(None, "clip", type_="foreignkey")  # type: ignore
    op.drop_column("clip", "keyword_id")
    op.drop_table("stream_keyword_association")
    op.drop_table("keyword")
    # ### end Alembic commands ###
