"""add is_active column to stream

Revision ID: e7019a700dc5
Revises: 8cc378d6d76e
Create Date: 2023-10-28 11:43:30.076928

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e7019a700dc5"
down_revision: Union[str, None] = "8cc378d6d76e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("stream", sa.Column("is_active", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stream", "is_active")
    # ### end Alembic commands ###
