"""add stream-table and rename clips to clip

Revision ID: ed2720873766
Revises: bc53b3eb3893
Create Date: 2023-08-13 16:43:58.981424

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ed2720873766"
down_revision: Union[str, None] = "bc53b3eb3893"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stream",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("channel_name", sa.String(length=255), nullable=True),
        sa.Column("broadcaster_id", sa.String(length=255), nullable=True),
        sa.Column("keyword_list", sa.String(length=1000), nullable=True),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "clip",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("clip_id", sa.String(length=255), nullable=True),
        sa.Column("stream_id", sa.Integer(), nullable=True),
        sa.Column("keyword_trigger", sa.String(length=255), nullable=True),
        sa.Column("keyword_count", sa.Integer(), nullable=True),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["stream_id"],
            ["stream.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("clips")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clips",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column("clip_id", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("channel_name", mysql.VARCHAR(length=255), nullable=True),
        sa.Column("keyword_trigger", mysql.VARCHAR(length=255), nullable=True),
        sa.Column(
            "keyword_count",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created",
            mysql.DATETIME(),
            server_default=sa.text("current_timestamp()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_general_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.drop_table("clip")
    op.drop_table("stream")
    # ### end Alembic commands ###
