name: Build and Deploy

on:
  push:
    tags: ["[0-9]+.[0-9]+.[0-9]+"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Trigger update on remote server
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -t rsa lwenstrom.net >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          echo $GITHUB_REF_NAME
          ssh jan@lwenstrom.net "bash ~/twitch-snapper/deployment/update_via_ci.sh $GITHUB_REF_NAME"
